# Generated by Django 5.2.8 on 2025-11-22 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('mercado', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factor', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instrumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calificaciones.instrumento')),
            ],
        ),
    ]
